global:
  scrape_interval: 15s  # Time between metric pulls

scrape_configs:
  - job_name: 'relayed-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']  