"""subscriptions_and_deliveries

Revision ID: 1317b3d76946
Revises: f85a60a95074
Create Date: 2026-06-26 16:56:44.279103

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1317b3d76946'
down_revision: Union[str, Sequence[str], None] = 'f85a60a95074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('destination_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('webhook_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DISABLED', name='subscriptionstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_customer_id'), 'subscription', ['customer_id'], unique=False)
    op.create_table('delivery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RETRYING', 'DELIVERED', 'DEAD_LETTERED', name='deliverystatusenum'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_customer_id'), 'delivery', ['customer_id'], unique=False)
    op.create_index(op.f('ix_delivery_event_id'), 'delivery', ['event_id'], unique=False)
    op.create_index(op.f('ix_delivery_subscription_id'), 'delivery', ['subscription_id'], unique=False)
    op.alter_column('customer', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('deadletter', sa.Column('subscription_id', sa.Uuid(), nullable=False))
    op.add_column('deadletter', sa.Column('delivery_id', sa.Uuid(), nullable=False))
    op.alter_column('deadletter', 'failed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('deadletter', 'replayed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_deadletter_delivery_id'), 'deadletter', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_deadletter_event_id'), 'deadletter', ['event_id'], unique=False)
    op.create_index(op.f('ix_deadletter_subscription_id'), 'deadletter', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'deadletter', 'delivery', ['delivery_id'], ['id'])
    op.create_foreign_key(None, 'deadletter', 'subscription', ['subscription_id'], ['id'])
    op.alter_column('event', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('event', 'destination_url')
    op.drop_column('event', 'next_attempt_at')
    op.drop_column('event', 'attempts')
    op.drop_column('event', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('next_attempt_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('destination_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('event', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'deadletter', type_='foreignkey')
    op.drop_constraint(None, 'deadletter', type_='foreignkey')
    op.drop_index(op.f('ix_deadletter_subscription_id'), table_name='deadletter')
    op.drop_index(op.f('ix_deadletter_event_id'), table_name='deadletter')
    op.drop_index(op.f('ix_deadletter_delivery_id'), table_name='deadletter')
    op.alter_column('deadletter', 'replayed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('deadletter', 'failed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('deadletter', 'delivery_id')
    op.drop_column('deadletter', 'subscription_id')
    op.alter_column('customer', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_delivery_subscription_id'), table_name='delivery')
    op.drop_index(op.f('ix_delivery_event_id'), table_name='delivery')
    op.drop_index(op.f('ix_delivery_customer_id'), table_name='delivery')
    op.drop_table('delivery')
    op.drop_index(op.f('ix_subscription_customer_id'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
