"""add tier column to customer

Revision ID: 993167d5957f
Revises: 4843809c7f81
Create Date: 2026-07-10 18:49:43.161788

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993167d5957f'
down_revision: Union[str, Sequence[str], None] = '4843809c7f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    tier_enum = sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='tierenum')
    tier_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'customer',
        sa.Column(
            'tier',
            tier_enum,
            nullable=False,
            server_default='FREE'
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'tier')
    # ### end Alembic commands ###
